from typing import Literal

# キー名をLiteralでまとめる
ErrorKey = Literal[
    "MissingRequiredParameter",
    "InvalidFormat",
    "ValueOutOfRange",
    "DuplicateInput",
    "RelatedResourceNotFound",
    "AuthenticationMissing",
    "AuthenticationFailed",
    "InsufficientPermissions",
    "SessionExpired",
    "MfaIncomplete",
    "AccountLocked",
    "RecordNotFound",
    "QueryError",
    "TransactionConflict",
    "DuplicateKeyError",
    "DatabaseConnectionFailed",
    "StorageFull",
    "ExternalApiAuthFailed",
    "ExternalApiInvalidResponse",
    "ExternalApiTimeout",
    "ExternalServiceDown",
    "ThirdPartySdkError",
    "ExternalSystemTemporaryLimit",
    "ServerInternalException",
    "InvalidConfigFile",
    "OutOfMemory",
    "DiskSpaceInsufficient",
    "ServiceStartupFailed",
    "InternalInconsistency",
    "NetworkConnectionFailed",
    "DnsResolutionFailed",
    "CommunicationTimeout",
    "LoadBalancingFailed",
    "InterServiceAuthError",
    "RequestLimitExceeded",
    "ApiKeyLimitExceeded",
    "BandwidthLimitExceeded",
    "TemporaryBlockForProtection",
    "UnknownError",
    "UnclassifiedSystemException",
    "FallbackError"
]
