events {}

http {
  server {
    listen 80;

    location /dreamer/ {
      proxy_pass http://dreamer-service:8000/;
    }

    location /job/ {
      proxy_pass http://job-service:8000/;
    }
  }
}
